user nginx;
worker_processes 1;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 256;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /dev/stdout;
    sendfile      on;
    keepalive_timeout 65;

    server {
        # Port dikonfigurasi dari $PORT oleh startup script
        listen 8000;
        root /var/www/html/public;
        index index.php index.html;

        # Charset
        charset utf-8;

        # Laravel routing
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # PHP via FPM
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # Sembunyikan file tersembunyi
        location ~ /\.(?!well-known).* {
            deny all;
        }

        # Upload max size
        client_max_body_size 2M;
    }
}
